// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/accounts_v1.proto

package protos

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorDescription struct {
	Type                 string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Category             string            `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Code                 string            `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	CorrelationId        string            `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Status               string            `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Message              string            `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Cause                string            `protobuf:"bytes,7,opt,name=cause,proto3" json:"cause,omitempty"`
	StackTrace           string            `protobuf:"bytes,8,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	Details              map[string]string `protobuf:"bytes,9,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ErrorDescription) Reset()         { *m = ErrorDescription{} }
func (m *ErrorDescription) String() string { return proto.CompactTextString(m) }
func (*ErrorDescription) ProtoMessage()    {}
func (*ErrorDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_292a892b22bf78d9, []int{0}
}

func (m *ErrorDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorDescription.Unmarshal(m, b)
}
func (m *ErrorDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorDescription.Marshal(b, m, deterministic)
}
func (m *ErrorDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorDescription.Merge(m, src)
}
func (m *ErrorDescription) XXX_Size() int {
	return xxx_messageInfo_ErrorDescription.Size(m)
}
func (m *ErrorDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorDescription.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorDescription proto.InternalMessageInfo

func (m *ErrorDescription) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ErrorDescription) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ErrorDescription) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ErrorDescription) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *ErrorDescription) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ErrorDescription) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ErrorDescription) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *ErrorDescription) GetStackTrace() string {
	if m != nil {
		return m.StackTrace
	}
	return ""
}

func (m *ErrorDescription) GetDetails() map[string]string {
	if m != nil {
		return m.Details
	}
	return nil
}

type PagingParams struct {
	Skip                 int64    `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take                 int32    `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	Total                bool     `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagingParams) Reset()         { *m = PagingParams{} }
func (m *PagingParams) String() string { return proto.CompactTextString(m) }
func (*PagingParams) ProtoMessage()    {}
func (*PagingParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_292a892b22bf78d9, []int{1}
}

func (m *PagingParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagingParams.Unmarshal(m, b)
}
func (m *PagingParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagingParams.Marshal(b, m, deterministic)
}
func (m *PagingParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagingParams.Merge(m, src)
}
func (m *PagingParams) XXX_Size() int {
	return xxx_messageInfo_PagingParams.Size(m)
}
func (m *PagingParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PagingParams.DiscardUnknown(m)
}

var xxx_messageInfo_PagingParams proto.InternalMessageInfo

func (m *PagingParams) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *PagingParams) GetTake() int32 {
	if m != nil {
		return m.Take
	}
	return 0
}

func (m *PagingParams) GetTotal() bool {
	if m != nil {
		return m.Total
	}
	return false
}

type Account struct {
	// Identification
	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Login string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	About string `protobuf:"bytes,4,opt,name=about,proto3" json:"about,omitempty"`
	// Activity tracking
	CreateTime string `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Deleted    bool   `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Active     bool   `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	// User preferences
	TimeZone string `protobuf:"bytes,8,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	Language string `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`
	Theme    string `protobuf:"bytes,10,opt,name=theme,proto3" json:"theme,omitempty"`
	// Custom fields
	CustomHdr            string   `protobuf:"bytes,11,opt,name=custom_hdr,json=customHdr,proto3" json:"custom_hdr,omitempty"`
	CustomDat            string   `protobuf:"bytes,12,opt,name=custom_dat,json=customDat,proto3" json:"custom_dat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_292a892b22bf78d9, []int{2}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

func (m *Account) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Account) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Account) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Account) GetTimeZone() string {
	if m != nil {
		return m.TimeZone
	}
	return ""
}

func (m *Account) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Account) GetTheme() string {
	if m != nil {
		return m.Theme
	}
	return ""
}

func (m *Account) GetCustomHdr() string {
	if m != nil {
		return m.CustomHdr
	}
	return ""
}

func (m *Account) GetCustomDat() string {
	if m != nil {
		return m.CustomDat
	}
	return ""
}

type AccountPage struct {
	Total                int64      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*Account `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AccountPage) Reset()         { *m = AccountPage{} }
func (m *AccountPage) String() string { return proto.CompactTextString(m) }
func (*AccountPage) ProtoMessage()    {}
func (*AccountPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_292a892b22bf78d9, []int{3}
}

func (m *AccountPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountPage.Unmarshal(m, b)
}
func (m *AccountPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountPage.Marshal(b, m, deterministic)
}
func (m *AccountPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPage.Merge(m, src)
}
func (m *AccountPage) XXX_Size() int {
	return xxx_messageInfo_AccountPage.Size(m)
}
func (m *AccountPage) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPage.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPage proto.InternalMessageInfo

func (m *AccountPage) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *AccountPage) GetData() []*Account {
	if m != nil {
		return m.Data
	}
	return nil
}

// The request message containing the account page request.
type AccountPageRequest struct {
	CorrelationId        string            `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Filter               map[string]string `protobuf:"bytes,2,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Paging               *PagingParams     `protobuf:"bytes,3,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AccountPageRequest) Reset()         { *m = AccountPageRequest{} }
func (m *AccountPageRequest) String() string { return proto.CompactTextString(m) }
func (*AccountPageRequest) ProtoMessage()    {}
func (*AccountPageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292a892b22bf78d9, []int{4}
}

func (m *AccountPageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountPageRequest.Unmarshal(m, b)
}
func (m *AccountPageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountPageRequest.Marshal(b, m, deterministic)
}
func (m *AccountPageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPageRequest.Merge(m, src)
}
func (m *AccountPageRequest) XXX_Size() int {
	return xxx_messageInfo_AccountPageRequest.Size(m)
}
func (m *AccountPageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPageRequest proto.InternalMessageInfo

func (m *AccountPageRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *AccountPageRequest) GetFilter() map[string]string {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *AccountPageRequest) GetPaging() *PagingParams {
	if m != nil {
		return m.Paging
	}
	return nil
}

// The response message containing the account page response
type AccountPageReply struct {
	Error                *ErrorDescription `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Page                 *AccountPage      `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AccountPageReply) Reset()         { *m = AccountPageReply{} }
func (m *AccountPageReply) String() string { return proto.CompactTextString(m) }
func (*AccountPageReply) ProtoMessage()    {}
func (*AccountPageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_292a892b22bf78d9, []int{5}
}

func (m *AccountPageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountPageReply.Unmarshal(m, b)
}
func (m *AccountPageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountPageReply.Marshal(b, m, deterministic)
}
func (m *AccountPageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPageReply.Merge(m, src)
}
func (m *AccountPageReply) XXX_Size() int {
	return xxx_messageInfo_AccountPageReply.Size(m)
}
func (m *AccountPageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPageReply.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPageReply proto.InternalMessageInfo

func (m *AccountPageReply) GetError() *ErrorDescription {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *AccountPageReply) GetPage() *AccountPage {
	if m != nil {
		return m.Page
	}
	return nil
}

// The request message containing the account id request.
type AccountIdRequest struct {
	CorrelationId        string   `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountIdRequest) Reset()         { *m = AccountIdRequest{} }
func (m *AccountIdRequest) String() string { return proto.CompactTextString(m) }
func (*AccountIdRequest) ProtoMessage()    {}
func (*AccountIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292a892b22bf78d9, []int{6}
}

func (m *AccountIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountIdRequest.Unmarshal(m, b)
}
func (m *AccountIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountIdRequest.Marshal(b, m, deterministic)
}
func (m *AccountIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountIdRequest.Merge(m, src)
}
func (m *AccountIdRequest) XXX_Size() int {
	return xxx_messageInfo_AccountIdRequest.Size(m)
}
func (m *AccountIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountIdRequest proto.InternalMessageInfo

func (m *AccountIdRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *AccountIdRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

// The request message containing the account login request.
type AccountLoginRequest struct {
	CorrelationId        string   `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Login                string   `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountLoginRequest) Reset()         { *m = AccountLoginRequest{} }
func (m *AccountLoginRequest) String() string { return proto.CompactTextString(m) }
func (*AccountLoginRequest) ProtoMessage()    {}
func (*AccountLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292a892b22bf78d9, []int{7}
}

func (m *AccountLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountLoginRequest.Unmarshal(m, b)
}
func (m *AccountLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountLoginRequest.Marshal(b, m, deterministic)
}
func (m *AccountLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountLoginRequest.Merge(m, src)
}
func (m *AccountLoginRequest) XXX_Size() int {
	return xxx_messageInfo_AccountLoginRequest.Size(m)
}
func (m *AccountLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountLoginRequest proto.InternalMessageInfo

func (m *AccountLoginRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *AccountLoginRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

// The request message containing the account object request.
type AccountObjectRequest struct {
	CorrelationId        string   `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Account              *Account `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountObjectRequest) Reset()         { *m = AccountObjectRequest{} }
func (m *AccountObjectRequest) String() string { return proto.CompactTextString(m) }
func (*AccountObjectRequest) ProtoMessage()    {}
func (*AccountObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292a892b22bf78d9, []int{8}
}

func (m *AccountObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountObjectRequest.Unmarshal(m, b)
}
func (m *AccountObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountObjectRequest.Marshal(b, m, deterministic)
}
func (m *AccountObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountObjectRequest.Merge(m, src)
}
func (m *AccountObjectRequest) XXX_Size() int {
	return xxx_messageInfo_AccountObjectRequest.Size(m)
}
func (m *AccountObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountObjectRequest proto.InternalMessageInfo

func (m *AccountObjectRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *AccountObjectRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

// The response message containing the account object response
type AccountObjectReply struct {
	Error                *ErrorDescription `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Account              *Account          `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AccountObjectReply) Reset()         { *m = AccountObjectReply{} }
func (m *AccountObjectReply) String() string { return proto.CompactTextString(m) }
func (*AccountObjectReply) ProtoMessage()    {}
func (*AccountObjectReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_292a892b22bf78d9, []int{9}
}

func (m *AccountObjectReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountObjectReply.Unmarshal(m, b)
}
func (m *AccountObjectReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountObjectReply.Marshal(b, m, deterministic)
}
func (m *AccountObjectReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountObjectReply.Merge(m, src)
}
func (m *AccountObjectReply) XXX_Size() int {
	return xxx_messageInfo_AccountObjectReply.Size(m)
}
func (m *AccountObjectReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountObjectReply.DiscardUnknown(m)
}

var xxx_messageInfo_AccountObjectReply proto.InternalMessageInfo

func (m *AccountObjectReply) GetError() *ErrorDescription {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *AccountObjectReply) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*ErrorDescription)(nil), "accounts.ErrorDescription")
	proto.RegisterMapType((map[string]string)(nil), "accounts.ErrorDescription.DetailsEntry")
	proto.RegisterType((*PagingParams)(nil), "accounts.PagingParams")
	proto.RegisterType((*Account)(nil), "accounts.Account")
	proto.RegisterType((*AccountPage)(nil), "accounts.AccountPage")
	proto.RegisterType((*AccountPageRequest)(nil), "accounts.AccountPageRequest")
	proto.RegisterMapType((map[string]string)(nil), "accounts.AccountPageRequest.FilterEntry")
	proto.RegisterType((*AccountPageReply)(nil), "accounts.AccountPageReply")
	proto.RegisterType((*AccountIdRequest)(nil), "accounts.AccountIdRequest")
	proto.RegisterType((*AccountLoginRequest)(nil), "accounts.AccountLoginRequest")
	proto.RegisterType((*AccountObjectRequest)(nil), "accounts.AccountObjectRequest")
	proto.RegisterType((*AccountObjectReply)(nil), "accounts.AccountObjectReply")
}

func init() { proto.RegisterFile("protos/accounts_v1.proto", fileDescriptor_292a892b22bf78d9) }

var fileDescriptor_292a892b22bf78d9 = []byte{
	// 825 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xde, 0x38, 0x7f, 0xce, 0x49, 0xb6, 0xea, 0x0e, 0x61, 0x65, 0x79, 0x29, 0x54, 0x96, 0x2a,
	0x8a, 0x10, 0x01, 0xc2, 0x0d, 0xf4, 0x8a, 0xb6, 0x29, 0xa2, 0x55, 0xa1, 0x91, 0x69, 0x25, 0x54,
	0x2e, 0xac, 0x89, 0x3d, 0xa4, 0xd3, 0x38, 0x1e, 0x33, 0x33, 0x8e, 0x14, 0x1e, 0x87, 0xb7, 0xe0,
	0x39, 0x78, 0x06, 0x24, 0x1e, 0x03, 0xcd, 0x8f, 0x53, 0xd3, 0xa4, 0x40, 0x56, 0xbd, 0x9b, 0xf3,
	0xf7, 0x9d, 0xe3, 0xf3, 0x7d, 0x33, 0x32, 0x78, 0x39, 0x67, 0x92, 0x89, 0x4f, 0x71, 0x1c, 0xb3,
	0x22, 0x93, 0x22, 0x5a, 0x7c, 0x3e, 0xd0, 0x2e, 0xe4, 0x96, 0xae, 0xe0, 0x4f, 0x07, 0x76, 0xcf,
	0x38, 0x67, 0x7c, 0x44, 0x44, 0xcc, 0x69, 0x2e, 0x29, 0xcb, 0x10, 0x82, 0x86, 0x5c, 0xe6, 0xc4,
	0xab, 0xed, 0xd7, 0x0e, 0x3b, 0xa1, 0x3e, 0x23, 0x1f, 0xdc, 0x18, 0x4b, 0x32, 0x65, 0x7c, 0xe9,
	0x39, 0xda, 0xbf, 0xb2, 0x55, 0x7e, 0xcc, 0x12, 0xe2, 0xd5, 0x4d, 0xbe, 0x3a, 0xa3, 0x03, 0xd8,
	0x89, 0x19, 0xe7, 0x24, 0xc5, 0x0a, 0x32, 0xa2, 0x89, 0xd7, 0xd0, 0xd1, 0x97, 0x15, 0xef, 0x79,
	0x82, 0x5e, 0x43, 0x4b, 0x48, 0x2c, 0x0b, 0xe1, 0x35, 0x75, 0xd8, 0x5a, 0xc8, 0x83, 0xf6, 0x9c,
	0x08, 0x81, 0xa7, 0xc4, 0x6b, 0xe9, 0x40, 0x69, 0xa2, 0x3e, 0x34, 0x63, 0x5c, 0x08, 0xe2, 0xb5,
	0xb5, 0xdf, 0x18, 0xe8, 0x03, 0xe8, 0x0a, 0x89, 0xe3, 0x59, 0x24, 0x39, 0x8e, 0x89, 0xe7, 0xea,
	0x18, 0x68, 0xd7, 0xb5, 0xf2, 0xa0, 0x63, 0x68, 0x27, 0x44, 0x62, 0x9a, 0x0a, 0xaf, 0xb3, 0x5f,
	0x3f, 0xec, 0x0e, 0x3f, 0x1c, 0x94, 0x4b, 0x18, 0x3c, 0x5e, 0xc0, 0x60, 0x64, 0x32, 0xcf, 0x32,
	0xc9, 0x97, 0x61, 0x59, 0xe7, 0x1f, 0x41, 0xaf, 0x1a, 0x40, 0xbb, 0x50, 0x9f, 0x91, 0xa5, 0xdd,
	0x92, 0x3a, 0xaa, 0xd9, 0x16, 0x38, 0x2d, 0x88, 0xdd, 0x90, 0x31, 0x8e, 0x9c, 0x2f, 0x6b, 0xc1,
	0x25, 0xf4, 0xc6, 0x78, 0x4a, 0xb3, 0xe9, 0x18, 0x73, 0x3c, 0x17, 0x6a, 0x65, 0x62, 0x46, 0x73,
	0x5d, 0x5c, 0x0f, 0xf5, 0x59, 0xaf, 0x1d, 0xcf, 0x4c, 0x71, 0x33, 0xd4, 0x67, 0x85, 0x28, 0x99,
	0xc4, 0xa9, 0xde, 0xad, 0x1b, 0x1a, 0x23, 0xf8, 0xdd, 0x81, 0xf6, 0xb1, 0x99, 0x1e, 0xed, 0x80,
	0x43, 0x13, 0x3b, 0x84, 0x43, 0x13, 0x55, 0x91, 0xb2, 0x29, 0xcd, 0xca, 0x19, 0xb4, 0xa1, 0xb0,
	0x33, 0x3c, 0x5f, 0x51, 0xa4, 0xce, 0x2a, 0x13, 0x4f, 0x58, 0x21, 0x2d, 0x33, 0xc6, 0x50, 0x9b,
	0x8c, 0x39, 0xc1, 0x92, 0x44, 0x92, 0xce, 0x89, 0xa5, 0x05, 0x8c, 0xeb, 0x9a, 0xce, 0x89, 0xa2,
	0x26, 0x21, 0x29, 0x91, 0x24, 0xd1, 0xd4, 0xb8, 0x61, 0x69, 0x2a, 0x32, 0x71, 0x2c, 0xe9, 0xc2,
	0x70, 0xe3, 0x86, 0xd6, 0x42, 0x6f, 0xa0, 0xa3, 0xb0, 0xa2, 0x5f, 0x59, 0x56, 0x52, 0xe3, 0x2a,
	0xc7, 0x2d, 0xcb, 0xb4, 0xb0, 0x52, 0x9c, 0x4d, 0x0b, 0x45, 0x75, 0xc7, 0xc4, 0x4a, 0x5b, 0x7f,
	0xfd, 0x1d, 0x99, 0x13, 0x0f, 0xcc, 0x84, 0xda, 0x40, 0x7b, 0x00, 0x71, 0x21, 0x24, 0x9b, 0x47,
	0x77, 0x09, 0xf7, 0xba, 0x3a, 0xd4, 0x31, 0x9e, 0x6f, 0x13, 0x5e, 0x09, 0x27, 0x58, 0x7a, 0xbd,
	0x6a, 0x78, 0x84, 0x65, 0x70, 0x01, 0x5d, 0xbb, 0xba, 0x71, 0xd9, 0x42, 0x2f, 0xd8, 0x30, 0x61,
	0x0c, 0x74, 0x00, 0x8d, 0x04, 0x4b, 0xec, 0x39, 0x5a, 0x2a, 0xaf, 0x1e, 0xa4, 0x62, 0x4b, 0x43,
	0x1d, 0x0e, 0xfe, 0xaa, 0x01, 0xaa, 0x80, 0x85, 0xe4, 0x97, 0x82, 0x08, 0xb9, 0x41, 0xfb, 0xb5,
	0x4d, 0xda, 0xff, 0x1a, 0x5a, 0x3f, 0xd3, 0x54, 0x12, 0x6e, 0xdb, 0x1c, 0xae, 0xb5, 0xa9, 0x80,
	0x0e, 0xbe, 0xd1, 0xa9, 0x46, 0x92, 0xb6, 0x0e, 0x0d, 0xa0, 0x95, 0x6b, 0x55, 0x69, 0x5e, 0xbb,
	0xc3, 0xd7, 0x0f, 0x08, 0x55, 0xb5, 0x85, 0x36, 0xcb, 0xff, 0x0a, 0xba, 0x15, 0x98, 0xad, 0x04,
	0xcc, 0x60, 0xf7, 0x1f, 0x43, 0xe5, 0xe9, 0x12, 0x7d, 0x06, 0x4d, 0xa2, 0xae, 0x8e, 0x46, 0xe8,
	0x0e, 0xfd, 0xa7, 0x6f, 0x54, 0x68, 0x12, 0xd1, 0x47, 0xd0, 0xc8, 0x15, 0xd1, 0x8e, 0x2e, 0x78,
	0x77, 0xf3, 0x07, 0xeb, 0x94, 0xe0, 0xc7, 0x55, 0xc3, 0xf3, 0x64, 0xcb, 0xc5, 0xee, 0x01, 0x58,
	0x60, 0x95, 0x62, 0x3e, 0xa5, 0x83, 0x4b, 0xb0, 0x20, 0x84, 0x77, 0x2c, 0xf2, 0xa5, 0xba, 0x1b,
	0x5b, 0x82, 0x6f, 0xbc, 0x5f, 0xc1, 0x3d, 0xf4, 0x2d, 0xe6, 0xd5, 0xe4, 0x9e, 0xc4, 0x72, 0x4b,
	0xd0, 0x8f, 0xa1, 0x6d, 0xe7, 0xb3, 0xab, 0xd9, 0x20, 0xb9, 0x32, 0x23, 0x10, 0x2b, 0xd1, 0x95,
	0xbd, 0xde, 0x8e, 0x8c, 0x6d, 0x9a, 0x0e, 0xff, 0x68, 0x80, 0x6b, 0x9d, 0x02, 0x5d, 0x40, 0x6f,
	0x4a, 0x64, 0x54, 0x66, 0xa3, 0xf7, 0xfe, 0x4d, 0xb9, 0xbe, 0xff, 0x44, 0x34, 0x4f, 0x97, 0xc1,
	0x0b, 0x74, 0x05, 0xaf, 0x2a, 0x58, 0xd1, 0x64, 0x19, 0xd1, 0x04, 0xad, 0x97, 0xac, 0x44, 0xe0,
	0xaf, 0x37, 0xab, 0xac, 0x21, 0x78, 0x81, 0x6e, 0xa0, 0xff, 0x08, 0xd0, 0x3c, 0x81, 0x7b, 0x6b,
	0x75, 0x55, 0xfa, 0xff, 0x13, 0xf6, 0x27, 0xf0, 0xd7, 0xe6, 0x8c, 0x18, 0x7f, 0x1e, 0xf0, 0x31,
	0xec, 0xd8, 0x47, 0xd7, 0xe6, 0xa1, 0xf7, 0x9f, 0xac, 0xf8, 0xdf, 0x88, 0x45, 0x9e, 0x3c, 0x27,
	0x62, 0x08, 0x7d, 0xf3, 0xd0, 0x3f, 0x1f, 0x57, 0x27, 0x67, 0xf0, 0x26, 0xa7, 0xf9, 0x27, 0x82,
	0xf0, 0x05, 0x8d, 0x89, 0x18, 0x14, 0x82, 0x70, 0xb1, 0xaa, 0x39, 0x79, 0x59, 0x2a, 0x6e, 0xac,
	0x7e, 0x5b, 0xc6, 0xb5, 0xdb, 0x96, 0xf9, 0xa5, 0xf9, 0xcd, 0xe9, 0x1d, 0x9f, 0x9e, 0x5e, 0xdd,
	0x7c, 0x7f, 0xfd, 0x43, 0x74, 0xfa, 0xdd, 0x68, 0x62, 0xdc, 0x5f, 0xfc, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0xeb, 0xd8, 0x91, 0x85, 0xf2, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountsClient is the client API for Accounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsClient interface {
	GetAccounts(ctx context.Context, in *AccountPageRequest, opts ...grpc.CallOption) (*AccountPageReply, error)
	GetAccountById(ctx context.Context, in *AccountIdRequest, opts ...grpc.CallOption) (*AccountObjectReply, error)
	GetAccountByLogin(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountObjectReply, error)
	GetAccountByIdOrLogin(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountObjectReply, error)
	CreateAccount(ctx context.Context, in *AccountObjectRequest, opts ...grpc.CallOption) (*AccountObjectReply, error)
	UpdateAccount(ctx context.Context, in *AccountObjectRequest, opts ...grpc.CallOption) (*AccountObjectReply, error)
	DeleteAccountById(ctx context.Context, in *AccountIdRequest, opts ...grpc.CallOption) (*AccountObjectReply, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) GetAccounts(ctx context.Context, in *AccountPageRequest, opts ...grpc.CallOption) (*AccountPageReply, error) {
	out := new(AccountPageReply)
	err := c.cc.Invoke(ctx, "/accounts.Accounts/get_accounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) GetAccountById(ctx context.Context, in *AccountIdRequest, opts ...grpc.CallOption) (*AccountObjectReply, error) {
	out := new(AccountObjectReply)
	err := c.cc.Invoke(ctx, "/accounts.Accounts/get_account_by_id", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) GetAccountByLogin(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountObjectReply, error) {
	out := new(AccountObjectReply)
	err := c.cc.Invoke(ctx, "/accounts.Accounts/get_account_by_login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) GetAccountByIdOrLogin(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountObjectReply, error) {
	out := new(AccountObjectReply)
	err := c.cc.Invoke(ctx, "/accounts.Accounts/get_account_by_id_or_login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) CreateAccount(ctx context.Context, in *AccountObjectRequest, opts ...grpc.CallOption) (*AccountObjectReply, error) {
	out := new(AccountObjectReply)
	err := c.cc.Invoke(ctx, "/accounts.Accounts/create_account", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) UpdateAccount(ctx context.Context, in *AccountObjectRequest, opts ...grpc.CallOption) (*AccountObjectReply, error) {
	out := new(AccountObjectReply)
	err := c.cc.Invoke(ctx, "/accounts.Accounts/update_account", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) DeleteAccountById(ctx context.Context, in *AccountIdRequest, opts ...grpc.CallOption) (*AccountObjectReply, error) {
	out := new(AccountObjectReply)
	err := c.cc.Invoke(ctx, "/accounts.Accounts/delete_account_by_id", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsServer is the server API for Accounts service.
type AccountsServer interface {
	GetAccounts(context.Context, *AccountPageRequest) (*AccountPageReply, error)
	GetAccountById(context.Context, *AccountIdRequest) (*AccountObjectReply, error)
	GetAccountByLogin(context.Context, *AccountLoginRequest) (*AccountObjectReply, error)
	GetAccountByIdOrLogin(context.Context, *AccountLoginRequest) (*AccountObjectReply, error)
	CreateAccount(context.Context, *AccountObjectRequest) (*AccountObjectReply, error)
	UpdateAccount(context.Context, *AccountObjectRequest) (*AccountObjectReply, error)
	DeleteAccountById(context.Context, *AccountIdRequest) (*AccountObjectReply, error)
}

// UnimplementedAccountsServer can be embedded to have forward compatible implementations.
type UnimplementedAccountsServer struct {
}

func (*UnimplementedAccountsServer) GetAccounts(ctx context.Context, req *AccountPageRequest) (*AccountPageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccounts not implemented")
}
func (*UnimplementedAccountsServer) GetAccountById(ctx context.Context, req *AccountIdRequest) (*AccountObjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountById not implemented")
}
func (*UnimplementedAccountsServer) GetAccountByLogin(ctx context.Context, req *AccountLoginRequest) (*AccountObjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountByLogin not implemented")
}
func (*UnimplementedAccountsServer) GetAccountByIdOrLogin(ctx context.Context, req *AccountLoginRequest) (*AccountObjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountByIdOrLogin not implemented")
}
func (*UnimplementedAccountsServer) CreateAccount(ctx context.Context, req *AccountObjectRequest) (*AccountObjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (*UnimplementedAccountsServer) UpdateAccount(ctx context.Context, req *AccountObjectRequest) (*AccountObjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccount not implemented")
}
func (*UnimplementedAccountsServer) DeleteAccountById(ctx context.Context, req *AccountIdRequest) (*AccountObjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccountById not implemented")
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_GetAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/GetAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetAccounts(ctx, req.(*AccountPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_GetAccountById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetAccountById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/GetAccountById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetAccountById(ctx, req.(*AccountIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_GetAccountByLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetAccountByLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/GetAccountByLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetAccountByLogin(ctx, req.(*AccountLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_GetAccountByIdOrLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetAccountByIdOrLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/GetAccountByIdOrLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetAccountByIdOrLogin(ctx, req.(*AccountLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).CreateAccount(ctx, req.(*AccountObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).UpdateAccount(ctx, req.(*AccountObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_DeleteAccountById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).DeleteAccountById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/DeleteAccountById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).DeleteAccountById(ctx, req.(*AccountIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accounts.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get_accounts",
			Handler:    _Accounts_GetAccounts_Handler,
		},
		{
			MethodName: "get_account_by_id",
			Handler:    _Accounts_GetAccountById_Handler,
		},
		{
			MethodName: "get_account_by_login",
			Handler:    _Accounts_GetAccountByLogin_Handler,
		},
		{
			MethodName: "get_account_by_id_or_login",
			Handler:    _Accounts_GetAccountByIdOrLogin_Handler,
		},
		{
			MethodName: "create_account",
			Handler:    _Accounts_CreateAccount_Handler,
		},
		{
			MethodName: "update_account",
			Handler:    _Accounts_UpdateAccount_Handler,
		},
		{
			MethodName: "delete_account_by_id",
			Handler:    _Accounts_DeleteAccountById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/accounts_v1.proto",
}
