version: '3.3'

services:

  test:
    image: ${IMAGE}
    links:
      - service
    ports:
      - "8090:8090"

  service:
    image: pipdevs/pipdevs:1.0.0-6-rc
    links:
      - mongo
      - couchbase
    environment:
      - MONGO_ENABLED=true
      - MONGO_SERVICE_HOST=mongo
      - MONGO_SERVICE_PORT=27017
      - MONGO_DB=test
      - COUCHBASE_SERVICE_HOST=couchbase
      - COUCHBASE_SERVICE_PORT=8091
      - COUCHBASE_USER=Administrator
      - COUCHBASE_PASS=password

  mongo:
    image: mongo:latest

  couchbase:
    image: couchbase/server-sandbox:5.5.1
